version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: exoplanet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./univer-db.sql:/app/data/dump.sql
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - '8080:8080'

volumes:
  pgdata: